### ISSUE TITLE
IP Address command returns an empty string

### ISSUE THREAD

**Issue by cisse21** [chipmk/docker-mac-net-connect#14]
Architecture: `Apple M1 Pro`

Docker Compose file
```
version: "3.7"

services:
  d-transformer:
    depends_on:
      - metrics-exporter
    image: rudderlabs/rudder-transformer:latest 
```
Command 

` docker inspect rudder-server-d-transformer --format '{{.NetworkSettings.IPAddress}}'`

The command returns an empty IPAddress. Can anyone help me out with this on why this might be happening?
