### ISSUE TITLE
Unreachable container with Docker Desktop 4.39.0

### ISSUE THREAD

**Issue by alexandreh2ag** [chipmk/docker-mac-net-connect#49]
Hello,

We just find out an issue the last version of Docker Desktop v4.39.0.
After the upgrade we can't reach (ping) the containers with default network configuration.

We downgrade the version of Docker Desktop to v4.38.0 and everything works fine like usual.

We use docker-mac-net-connect version 0.1.3.

We find a solution to fix the problem. Just adding this parameter on network configuration seems to work:

```
networks:
  default:
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: nat-unprotected

  custom:
    name: my-custom
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: nat-unprotected
```
We did not tests every scenario.

I don't know if we can change something in docker-mac-net-connect to fix it but maybe it will be helpful to add a section in documentation about this.

Best regards.
Alex
